name: Deploy

on:
  push:
    branches:
      - master

job:
  build: 
    run-on: ubuntu-latest

    steps:
      - name: Chechout code
        run: action/checkout@v3
      
      - name: login to DockerHub
        run : docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker Image
        run: docker build -t tushar754/portfolio .

      - name: Publish to docker hub
        run: docker push tushar754/portfolio:latest
  
  deploy:
    needs: build
    run-on: aws-ec2

    steps:
      - name: pull image from docker hub
        run: docker pull tushar754/portfolio:latest

      - name: Delete old container
        run: docker rm -f portfolioContainer
      
      - name: Run docker container
        run docker run -d -p 3000:80 --name portfolioContainer tushar754/portfolio

